### ISSUE TITLE
hollywood poker pro settings

### ISSUE THREAD

**Issue by chrcoluk** [HoraceAndTheSpider/UAEConfigMaker#10]
This game should have fast copper disabled
cpu set to 68000
chipset set to OCS
speed set to 7mhz

The speed is needed as else the game is running too fast
The fast copper causes some graphical glitches

I am surprised you using 68020 and ECS for non AGA games.

Also forgot to mention change fast ram to slow ram to match what was in a500, not sure if this actually needed but should be used to be sure.

**Comment by HoraceAndTheSpider** [comment]
This won't work. WHDLoad requires 68010+ Minimum.
Same reason as to why fat ram is used not slow ram - whdload needs this ram to cache the game data.

Whdload is designed to run on above a500 standard machines, so a default "a600 with fastest and Hd" forms the lower spec. default.

**Comment by HoraceAndTheSpider** [comment]
I will check out the fast copper thing, although if you have tested it with that change alone you can contribute It directly to the settings file here on GitHub.

 It will then filter down to everyone's future Configs. Thanks for letting us know.

**Comment by chrcoluk** [comment]
well it works as I used it :)

**Comment by HoraceAndTheSpider** [comment]
Added to No Fast Copper list.
