### ISSUE TITLE
[HDF Data Only Mode] Screen_Height_240 settings file etc.

### ISSUE THREAD

**Issue by ghost** [HoraceAndTheSpider/UAEConfigMaker#15]
Why are all of these games set at 640x240 ? I tried some of these and they are all missing the bottom of the screen because of it. Why have they set these like this ?

**Comment by HoraceAndTheSpider** [comment]
Probably they fit but require Y-offset alignment - assuming you are referring to ones that are specifically set to this value and not just selected by default.

**Comment by blinkydoos** [comment]
Yes, the ones that are listed in the Screen_Height_240 settings file. The bottom of the screen is cut off. They should be the default 640x256 which fits.

**Comment by ghost** [comment]
I'm not sure actually, I tried a lot of AGA games and they all seem to be 640x240 resolution ? Is there a default resolution set wrong somewhere ? I am thinking that my uae configs are not getting these changes applied. Is the development version adding these changes to the UAE files ?

**Comment by ghost** [comment]
I just checked and it seems the settings text files are not being applied to my UAE configs.

**Comment by HoraceAndTheSpider** [comment]
Most likely cause is that it’s related to using HDFs.

I assume you are keeping the files named as per your previous example uploads

**Comment by ghost** [comment]
Yes, the HDF's are named the same as the slave file directories. It's renaming the UAE config files correctly so it must be detecting the correct name.

**Comment by blinkydoos** [comment]
Just to confirm, I tried 'Alien Breed 2 AGA' in directory mode which should set the Screen Height to 256 but in the UAE config file it says 704x262 ? So the Development version is not applying these ?

**Comment by HoraceAndTheSpider** [comment]
Please allow me time to investigate fully.

**Comment by tednilsen** [comment]
the Y offset list is tuned for PAL / 50Hz, so if you  @blinkydoos run in NTSC mode then the Y offset is incorrect.
maybe figure out the relation between PAL and NTSC modes, and how that affects the Y offset?

**Comment by HoraceAndTheSpider** [comment]
@tednilsen I think the offset value has been removed from the latest Amiberry, so I will be checking to see if there is an auto-alignment or similar planned.

**Comment by ghost** [comment]
@tednilsen Yes i'm a PAL 50Hz user so Y offset settings don't conflict. It's still an option in Amiberry SDL1 but the SDL2 version it has been removed and also Resolution Settings ! so this will make the Config Maker Resolution Settings obsolete (as well as Fast Copper). Currently though, I don't think any of the extra settings files are being applied to the UAE configs in the development version. I'm just waiting for @HoraceAndTheSpider to take a look when he has some free time.

**Comment by tednilsen** [comment]
i'm using horace's amiberry version now, and the new features added are really awesome.
auto-allignment will not work - it cannot work, even if you try. imagine all the demoscene products that utilizes all the c.o. chips and makes changes / wait scanline / copper several times in a single frame  - bad, bad idea'. it will work on most products - sure, but removing or adding an autofeature (without an option for manually setting the Y) is called a bug, not a feature...?

**Comment by ghost** [comment]
@tednilsen Yes I agree, but the last time I compiled the SDL2 version the Resolution Settings were removed  and also the Fast Copper setting. It's a shame, like you say, some demo's and games change resolution on the fly, i'm not sure how it works. When I tried it with Pinball Illusions the right ball lane was cut off the screen, probably standard 640x256 which is too low for that game. There was a bug report for that issue (my first bug report (https://github.com/midwan/amiberry/issues/100#issuecomment-303978138) but it has been closed. Maybe Midwan will add some customising options in the future. SDL1 version is fine.

**Comment by HoraceAndTheSpider** [comment]
Comments on auto sizing noted - I haven’t looked at SDL2 much myself but didn’t realise the auto size had led to a complete removal. 

I agree , we had similar issues with auto sizing  in PSPUAE, so I’ve spoken with Midwan to get these reinstated.

**Comment by ghost** [comment]
This is also fixed. I'll double check some more in a few hours then close this issue. Thanks.
