### ISSUE TITLE
Custom options from specific .ws files to be tested

### ISSUE THREAD

**Issue by ghost** [HoraceAndTheSpider/UAEConfigMaker#17]
Tooltypes are used in a few games to load Data Disks etc. For example -

BattleIsle&DataDisks

Intro = CUSTOM1=1
Main = CUSTOM1=3 (default)
Data1 = CUSTOM1=4
Data2 = CUSTOM1=5

PinballPreludeAGA

Past Table = CUSTOM1=0 (default)
Present Table = CUSTOM1=1
Future Table = CUSTOM1=2

**Comment by HoraceAndTheSpider** [comment]
This is more related to the WHD booter than the config maker (if i could create a seperate GitHub for it i would, but sadly AMOS code is not easily supported!)

However, this is not an issue - you can already set CUSTOM tooltypes using the WHD booter in its current state, by pressing 'space' or '2nd fire' on load up.  

If the slave author has added the CUSTOM tooltypes to the WHDLoad header ('ws_config' section, supported from WHDLoad V17+) then the booter already detects these from the slave.  See here for the technical detail of how this header is formed:  http://whdload.de/docs/autodoc.html#ws_config

For older slaves you can create your own load version of this header in a text named the same as the slave but ending `.ws`  (there are some examples already included in the booter package) 

Here is an example of the file you need for this to work with Pinball Prelude

`PinballPreludeAGA.ws`

```
C1:L:Prehistoric Table;Present Table;Future Table; 
C2:B:Quit with Left Mouse Button;
C3:B:Enable Enhanced High Score Support;
```

Hope that helps

**Comment by ghost** [comment]
Not really sure what's going on, for the Custom options I put above for Pinball Prelude AGA, I made a file called `PinballPreludeAGA.ws` in the `WHDBooter/WSConfigs` folder. In the file I put -

C0:B:Past Table;C1:B:Present Table;C2:B:Future Table;

I couldn't get anything to happen. What's the 'B' in the file as I noticed some of the examples had 'X' ?

**Comment by HoraceAndTheSpider** [comment]
You need to use the exact text I gave you... this is formed correctly for the details given in the Pinball Prelude readme. 

Not sure where you have got C0 from?

The C1 means “provide an option for custom 1”
The L then tells it to use a list, and what to name each item in the list.

The B is used to denote a simple “button” ie on/off as =0/1

The X uses the bit mask notation - very similar to the above except you need to specify which “bit” you are switching on/off. This is done on a lot of slaves in order to give more options within a Single CUSTOM option on, since there is a maximum of 5 only.

edit: i have just noticed that the 'mark up' styling of the above had hidden the custom 1 list, which i have just changed so it is visible now.

**Comment by ghost** [comment]
Thanks, I can understand it now that you edited the post ! (I thought C0 was for Custom1=0),

**Comment by ghost** [comment]
Couldn't get it to work. I put what you said in `PinballPreludeAGA.ws` and tried pressing button 2 or space while booting but got a black screen.

**Comment by HoraceAndTheSpider** [comment]
You need to hold a 'regular' fire button to bring the WHDBooter back up.

If the file is correctly named, then after the slave selection you will see the extra text at the bottom like this:

http://www.ultimateamiga.co.uk/HostedProjects/RetroPieAmiga/guide/WHDBoot_2.png


After pressing space/second fire, you'll be able to see the following screen, with the settings provided.

http://www.ultimateamiga.co.uk/HostedProjects/RetroPieAmiga/guide/WHDBoot_3.png

**Comment by ghost** [comment]
Noted, it's button 1 to bring the Booter back up, but when pressing button 2 (or space) I get a black screen.

**Comment by HoraceAndTheSpider** [comment]
Sounds like it can see the file but not read it - check you have permissions on the ws file set correctly for the Pi user.

**Comment by ghost** [comment]
I reset permissions of the roms directory but still only a black screen. Maybe you could try it when you have some free time and let me know.

**Comment by HoraceAndTheSpider** [comment]
I use this function on a few games, so I know it does work. You will need to post a copy of the file you created perhaps.

It could also be down to which text editor you use (NotePad on Windows for example is notorious for not being the same format as others)

**Comment by ghost** [comment]
Something I noticed earlier was that if I select custom options in the booter (for games that have them), even if I don't change any options the game doesn't boot, just a black screen. I tried 4 games with custom options and all 4 I had to re-enable/reset the boot menu before it would load again.

**Comment by HoraceAndTheSpider** [comment]
Please check that this is not related to using HDFs.

I am unable to reproduce this bug. Tested Dalek Attack (uses .ws file) and Bloodwych (uses WHD Header) and both working ok.

**Comment by ghost** [comment]
I must have been lucky/unlucky finding 4 games in a row yesterday, today I had trouble finding any games with built in Custom Options ! I tried the following with Directory Mode and WHDLoad HDF mode -

Afterburner (Sega) - Works in Both
Alien Breed 2 - Works in Both
Super Stardust AGA - Works in Both
Jaguar XJ220 - Doesn't work at all (but I think it needs Cycle Accuracy anyway)
Pinball Prelude AGA (with custom added .ws file in the WSConfigs folder) - Doesn't work in Either

I can't remember the other games I found yesterday.

This is what you told me to enter in this file -
[PinballPreludeAGA.zip](https://github.com/HoraceAndTheSpider/UAEConfigMaker/files/1551361/PinballPreludeAGA.zip)
(I also tried it all in one line without carriage returns).

**Comment by ghost** [comment]
Did you ever get round to trying the PinballPreludeAGA.ws file ?

I found a few more that don't work when going to the Custom Options, Batman The Movie, Shadow Of The Beast & Mega-lo-mania. I tried RareJ's bootloader and all the games I listed here work fine (including Jaguar XJ220).

**Comment by HoraceAndTheSpider** [comment]
In summary:

>> Pinball Prelude AGA (with custom added .ws file in the WSConfigs folder)
>> Batman The Movie 
>> Shadow Of The Beast 
>> Mega-lo-mania

**Comment by HoraceAndTheSpider** [comment]
Mega-lo-mania v1.7 [in built ws] - No issue with the booter - i could not navigate the menu with the default settings because the game had mapped to mouse port by default, but was still in joystick mode, so the issue there is not related to the Booter itself.

Batman The Movie v1.5 [in built ws] - Cannot reproduce any problem - tried with and without cheats.

Pinball Prelude requires a change of syntax for the .ws file:

```
C1:L:Select Table:Prehistoric,Present,Future;
C2:B:Quit with Left Mouse Button;
C3:B:Enable Enhanced High Score;
```

Shadow Of The Beast appears to work with the in built .ws to skip intro only (the readme refers to another custom setting which is not included, to remove blitwaits - possibly should be reported through Mantis WHD bug tracker)

**Comment by ghost** [comment]
I'll check these again tomorrow, in Folder Mode and Data Only HDF.

Did you try the 1 Disk version of Batman the Movie and did you have any luck with Jaguar XJ220 ?

**Comment by ghost** [comment]
PinballPrelude can now change table with this fix but I can't change the other options, and if I select Present Table then 'Quit with Mouse button' and 'High score support' turn on and I can't turn it off.

**Comment by HoraceAndTheSpider** [comment]
To turn it off I assume you are reloading the booter? 
Or do you mean you can’t turn it off on the custom selection screen ?

**Comment by ghost** [comment]
I can't change the options in the Custom from No to Yes etc. Only the Table can be changed and they all turn Yes when the Present Table is selected.

Regarding the other issues reported, I tried Batman, Megalomania, and ShadowOfTheBeast again in HDF Data only and now they all work when selecting the custom options ! Did you fix this ? Has it got something to do with the new scanning method you implemented ?

**Comment by HoraceAndTheSpider** [comment]
I honestly don’t know why they wouldn’t have worked before, but glad they do.

I have some ideas re: Pinball prelude but I will check that out. 

I will need to resolve the default setting for MLM too as another of my favourites.

**Comment by ghost** [comment]
When you've worked it out could you also show me an example .ws for BattleIsle&DataDisks as listed in the first post ?

I found another minor issue when I tried the Folder scanning mode, i'll let you know in a separate issue.

**Comment by HoraceAndTheSpider** [comment]
Jaguar XJ220 problem is caused by an inconsistency between the slave header, and the way the game is installed.

Logged here:  http://mantis.whdload.de/view.php?id=3831
