### ISSUE TITLE
JIT OFF as default ?

### ISSUE THREAD

**Issue by ghost** [HoraceAndTheSpider/UAEConfigMaker#20]
Did you say you were going to turn JIT off as default ? There are 420 games ! in the `CPU_NoJIT` file and I don't really see any need for it to be on, mainly for 3D games and you also need CPU Fastest for it to benefit.

I just found another that needs JIT Off, Thundercats. If it's ON then you keep repeatedly dying.

**Comment by HoraceAndTheSpider** [comment]
Should be changed on the latest commits.

**Comment by ghost** [comment]
I'll close this now.
