### ISSUE TITLE
Aspect Ratio / Screen Size Improvements

### ISSUE THREAD

**Issue by ghost** [HoraceAndTheSpider/UAEConfigMaker#22]
Not really an issue but i'd just point out that all games listed in `Screen_Height_200.txt` will only look correct when viewed in Widescreen. If you are at 4:3 then it just basically stretches the image vertically. Maybe an option to force 4:3 Off for all games listed in this file (for people who have Force 4:3 aspect on) ? Screen Height 216 might look acceptable in Widescreen too, but haven't checked.

Not sure what would happen when using a 4:3 monitor ?

**Comment by tednilsen** [comment]
Most games are meant to fill out the screen, some few games are not - this is the horror story of amiga and the PAL / NTSC conversions I guess. Take Monkey Island, we all played it on the amiga with our PAL machine but never experienced a "full screen" image on our monitor - but the game itself was made for fullscreen stretch, just launch scummvm or the DOS version of the game and experience it yourself.

Yeah, the Amiga and aspect ratio is a mess... But most (not all) 200px where meant to fill the monitor with 4:3 ar.

**Comment by ghost** [comment]
But that's how it was on the Amiga, for example (not my picture) -
![lotus](https://user-images.githubusercontent.com/27903587/33936119-4fd48834-dff6-11e7-8e39-5076be30319b.jpg)
Note the big black bar at the bottom. If you lower the original resolution to NTSC 640x200 then it stretches the image vertically. It will look better on Widescreen because it will also stretch it horizontally and give almost the original aspect. This is similar to WinUAE's Autoscale.

**Comment by tednilsen** [comment]
I disagree. The aspect was meant to fill the entire screen, not having the black bar at the bottom (we are used to seeing that black bar on many games on amiga, that does not mean it is correct).
Here are Lotus The Ultimate Challenge:

dos:
http://www.mobygames.com/game/dos/lotus-the-ultimate-challenge/screenshots/gameShotId,8808/

genesis:
http://www.mobygames.com/game/genesis/lotus-the-ultimate-challenge/screenshots/gameShotId,109723/

amiga:
http://www.mobygames.com/game/amiga/lotus-the-ultimate-challenge/screenshots/gameShotId,159594/

The DOS and Genesis version is meant to fill the entire screen, and it have the same video resolution as the amiga (remove the top/bottom 24px on Genesis).... So the amiga version must have a unique aspect-ratio then?
Nope... sorry, we where all deceived in our youth :)

Also remember that many games where made in the US, and no 256px video resolution there - but NTSC standard: 200px.

**Comment by ghost** [comment]
Yes but look at the aspect ratio of the car on the Amiga picture you posted []((http://www.mobygames.com/game/amiga/lotus-the-ultimate-challenge/screenshots/gameShotId,159594/)) and in particular the circular road sign. If you stretched the image vertically to remove the black bars the road sign will become an oval shape ! (Magnetic Fields is a British company).

Here is an interesting read -
http://eab.abime.net/showthread.php?t=87698&styleid=4&styleid=1

@HoraceAndTheSpider What do you think about this ?

**Comment by tednilsen** [comment]
I agree, and several games had the graphics drawn in the wrong aspect-ratio. There is no one solution, one answer to this as some games where meant to be stretched (allready said: monkey island).

My best solution:
Filter games with the resolution of <= 240px to stretch to 240px, this can be done easy in the script.
What do you think?

**Comment by HoraceAndTheSpider** [comment]
My preference is always to fill the screen as much as possible. This is why I am not often fussed about the aspect ratio option, but appreciate the user preference  for it.

I Need to read through this properly tonight, but are you basically suggesting a three way aspect ratio option...  


- Widescreen (no aspext fix) and screen widths used
- aspect fix on everything (so called “purist” option)
- aspect fix on everything except height<= 240

**Comment by ghost** [comment]
Yes, so what you said in the above post, is it possible to add ? So currently there is -

Correct aspect=false (Everything stretched widescreen)
Correct aspect=true (correct 4:3 for everything except screen height 200 & 216)

then a third option for 4:3 users that will turn OFF correct aspect for all games listed in Screen height 216 and 200 ? This will then give almost the correct aspect but full widescreen. Although I think the screen width may need to be 704 to give an inch black on each side. This makes it look the same correct aspect as WinUAE's automatic scaling feature.

**Comment by HoraceAndTheSpider** [comment]
This problem may be resolved from the latest update to Amiberry, which has new aspect ratio options which will not 'force' 4:3, therefore hopefully solving the issue of stretching when correct-aspect is used.

As such, i will be holding-off on implementing these, as it may not be needed.

**Comment by ghost** [comment]
I've tried the new version and the aspect correction is a very good new feature ! It does what I asked for but more accurately. This can now be closed.
