### ISSUE TITLE
Add gfx_linemode to hostconfig

### ISSUE THREAD

**Issue by ghost** [HoraceAndTheSpider/UAEConfigMaker#26]
Hi, I don't know if this is an incompatibility with the config maker or a problem with Amiberry. I built the latest DEV SDL1 version yesterday but now the joypad buttons don't work (in game). The D-Pad works fine. I wondered if the RetroArch control file is being read correctly. I left a report on Amiberry GitHub as well but not sure of the cause. Have you tried a recent version ?

EDIT: Another quick question while i'm here. Is 'Line Doubling' now turned OFF by default because of performance issues ? It makes the screen a lot clearer and less blurry on everything. There's no sign of this option in the ConfigMaker though.

**Comment by HoraceAndTheSpider** [comment]
I think this needs directing towards the Amiberry github page instead? 

As you say, i havent put anything in for libe doubling as I find it works ok by default. If someone can tell me the syntax i can add the option

**Comment by ghost** [comment]
gfx_linemode=double
or
gfx_linemode=none

I don't know if Midwan disabled it by default because of performance ? It makes the screen less blurry.

**Comment by ghost** [comment]
Midwan has just confirmed that the Joypad buttons don't work so not a problem with configmaker.

**Comment by HoraceAndTheSpider** [comment]
Fixed in commit 40669e4
