### ISSUE TITLE
Updater does not work

### ISSUE THREAD

**Issue by quantum8** [HoraceAndTheSpider/UAEConfigMaker#57]
I have previously installed using the instructions in the readme. When I try running the update script I get a file not found error. Not sure if it's intentional or not but it makes it look like things are broken.

<code>pi@retropie:~/.uaeconfigmaker $ python3 update_config_maker.py

HoraceAndTheSpider's UAE Configuration Maker (Auto-Update) | www.ultimateamiga.co.uk

Update downloaded for uae_config_maker.py.
No update downloaded for UAE%20Config%20Maker.sh. (Web Page not found)
Update downloaded for README.md.
Update downloaded for TODO.md.
Update downloaded for whdload/whdload_slave.py.
Update downloaded for utils/general_utils.py.
Update downloaded for utils/text_utils.py.
Update downloaded for utils/update_utils.py.</code>

**Comment by HoraceAndTheSpider** [comment]
Hi

It is the which is installed to the RetroPie menu.

I am not sure why it doesn’t download (probably to do with spaces in the filename) but it is part of the install on the readme anyway.

So... yes, it’s a bug, but at the same time it will not stop anything from working :)
