### ISSUE TITLE
Tips and Guide for adding to /settings/

### ISSUE THREAD

**Issue by GreenRebel** [HoraceAndTheSpider/UAEConfigMaker#7]
Hi, I see you have CPU_No24BitAddress.txt but what if a game needed to have this option checked. Should there be a CPU_Yes24BitAddress.txt or will script just set to yes everything except those mentioned in  CPU_No24BitAddress.txt (however I dont think this is the case from my experience).

**Comment by HoraceAndTheSpider** [comment]
The option is ON by default - for these options which are just boolean, I only have a setting for an override from the default behaviour.
(In this case to set "false") ... I will double check the default behaviour is performing correctly though

**Comment by HoraceAndTheSpider** [comment]
Looks like this is defaulting to "false" so I will have to look into this... thanks :)

**Comment by GreenRebel** [comment]
Cheers. And is there a file where we can set to disable 'Frameskip' , under display settings?

**Comment by HoraceAndTheSpider** [comment]
Host option "gfx_framerate" will do this :)

The 24 bit addressing is certainly  bugged (it is muddled with the cycle exact option that possible doesn't work in amiberry anyway)
I can probably fix it even from my phone ;)

**Comment by HoraceAndTheSpider** [comment]
Should be fixed, but I won't close until I have built new files to test 

Thanks

**Comment by HoraceAndTheSpider** [comment]
Looks like this is now defaulting to 'true' as it should. I have no games on the CPU_No24BitAddress.txt list however, but I am closing this as fixed :)
