### ISSUE TITLE
War Zone (core) 

### ISSUE THREAD

**Issue by Fable-Son** [HoraceAndTheSpider/UAEConfigMaker#8]
Hey

I tried changing a bunch of stuff. Also tried downloading a new slave file. It didn't help a thing.

Do you have any ideas? Is the game broken? 

Here is a link to my Facebook post where you can se a video of the poblem
https://www.facebook.com/groups/1854320841462593/permalink/1994254264135916/

**Comment by HoraceAndTheSpider** [comment]
This is an emulator compatibility issue. 24-bit addressing being switch OFF seems to change the graphic display, but then causes the emulator to crash. This should be reported via the Amiberry or uae4arm pages, rather than here.
