### ISSUE TITLE
Street Rod / Cannon Fodder

### ISSUE THREAD

**Issue by Fable-Son** [HoraceAndTheSpider/UAEConfigMaker#9]
In games like Cannon Fodder and Street Rod, I can either move the mouse arrow, or use the mouse buttons. But not both a once... Depending on what settings I set it to in "Input".
Is there anyway to set those games up so they can be played with a controler ?

**Comment by HoraceAndTheSpider** [comment]
This is again an Amiberry/emulator issue, and not related to the Config Maker, so not much help here I'm afraid to say.

There is currently no mapping of mouse functions to the joypad. The default option should be set to use your mouse/trackpad input as the Amiga mouse.

For Cannon Fodder, I recommend using the cd32 version which allows a joypad to be used instead. I don't know anything about Street Rod though.
